package io.github.kasperknop.pokedb;

import java.util.ArrayList;
import java.util.List;

public class PokemonDB {

    List<Pokemon> pokemonList = new ArrayList<>();

    public PokemonDB(){
        pokemonList.add(new Pokemon(1, "Bulbasaur", "GRASS", "POISON", "1.png"));
        pokemonList.add(new Pokemon(2, "Ivysaur", "GRASS", "POISON", "2.png"));
        pokemonList.add(new Pokemon(3, "Venusaur", "GRASS", "POISON", "3.png"));
        pokemonList.add(new Pokemon(4, "Charmander", "FIRE", null, "4.png"));
        pokemonList.add(new Pokemon(5, "Charmeleon", "FIRE", null, "5.png"));
        pokemonList.add(new Pokemon(6, "Charizard", "FIRE", "FLYING", "6.png"));
        pokemonList.add(new Pokemon(7, "Squirtle", "WATER", null, "7.png"));
        pokemonList.add(new Pokemon(8, "Wartortle", "WATER", null, "8.png"));
        pokemonList.add(new Pokemon(9, "Blastoise", "WATER", null, "9.png"));
        pokemonList.add(new Pokemon(10, "Caterpie", "BUG", null, "10.png"));
        pokemonList.add(new Pokemon(11, "Metapod", "BUG", null, "11.png"));
        pokemonList.add(new Pokemon(12, "Butterfree", "BUG", "FLYING", "12.png"));
        pokemonList.add(new Pokemon(13, "Weedle", "BUG", "POISON", "13.png"));
        pokemonList.add(new Pokemon(14, "Kakuna", "BUG", "POISON", "14.png"));
        pokemonList.add(new Pokemon(15, "Beedrill", "BUG", "POISON", "15.png"));
        pokemonList.add(new Pokemon(16, "Pidgey", "NORMAL", "FLYING", "16.png"));
        pokemonList.add(new Pokemon(17, "Pidgeotto", "NORMAL", "FLYING", "17.png"));
        pokemonList.add(new Pokemon(18, "Pidgeot", "NORMAL", "FLYING", "18.png"));
        pokemonList.add(new Pokemon(19, "Rattata", "NORMAL", null, "19.png"));
        pokemonList.add(new Pokemon(20, "Raticate", "NORMAL", null, "20.png"));
        pokemonList.add(new Pokemon(21, "Spearow", "POISON", "FLYING", "21.png"));
        pokemonList.add(new Pokemon(22, "Fearow", "NORMAL", "FLYING", "22.png"));
        pokemonList.add(new Pokemon(23, "Ekans", "POISON", null, "23.png"));
        pokemonList.add(new Pokemon(24, "Arbok", "POISON", null, "24.png"));
        pokemonList.add(new Pokemon(25, "Pikachu", "ELECTRIC", null, "25.png"));
        pokemonList.add(new Pokemon(26, "Raichu", "ELECTRIC", null, "26.png"));
        pokemonList.add(new Pokemon(27, "Sandshrew", "GROUND", null, "27.png"));
        pokemonList.add(new Pokemon(28, "Sandslash", "GROUND", null, "28.png"));
        pokemonList.add(new Pokemon(29, "Nidoran♀", "POISON", null, "29.png"));
        pokemonList.add(new Pokemon(30, "Nidorina", "POISON", null, "30.png"));
        pokemonList.add(new Pokemon(31, "Nidoqueen", "POISON", "GROUND", "31.png"));
        pokemonList.add(new Pokemon(32, "Nidoran♂", "POISON", null, "32.png"));
        pokemonList.add(new Pokemon(33, "Nidorino", "POISON", null, "33.png"));
        pokemonList.add(new Pokemon(34, "Nidoking", "POISON", "GROUND", "34.png"));
        pokemonList.add(new Pokemon(35, "Clefairy", "FAIRY", null, "35.png"));
        pokemonList.add(new Pokemon(36, "Clefable", "FAIRY", null, "36.png"));
        pokemonList.add(new Pokemon(37, "Vulpix", "FIRE", null, "37.png"));
        pokemonList.add(new Pokemon(38, "Nintales", "FIRE", null, "38.png"));
        pokemonList.add(new Pokemon(39, "Jigglypuff", "NORMAL", "FAIRY", "39.png"));
        pokemonList.add(new Pokemon(40, "Wigglytuff", "NORMAL", "FAIRY", "40.png"));
        pokemonList.add(new Pokemon(41, "Zubat", "POISON", "FLYING", "41.png"));
        pokemonList.add(new Pokemon(42, "Golbat", "POISON", "FLYING", "42.png"));
        pokemonList.add(new Pokemon(43, "Oddish", "GRASS", "POISON", "43.png"));
        pokemonList.add(new Pokemon(44, "Gloom", "GRASS", "POISON", "44.png"));
        pokemonList.add(new Pokemon(45, "Vileplume", "GRASS", "POISON", "45.png"));
        pokemonList.add(new Pokemon(46, "Paras", "BUG", "GRASS", "46.png"));
        pokemonList.add(new Pokemon(47, "Parasect", "BUG", "GRASS", "47.png"));
        pokemonList.add(new Pokemon(47, "Venonat", "BUG", "POISON", "48.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "49.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "50.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "51.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "52.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "53.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "54.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "55.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "56.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "57.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "58.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "59.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "60.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "61.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "62.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "63.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "64.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "65.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "66.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "67.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "68.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "69.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "70.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "71.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "72.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "73.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "74.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "75.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "76.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "77.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "78.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "79.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "80.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "81.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "82.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "83.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "84.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "85.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "86.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "87.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "88.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "89.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "90.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "91.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "92.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "93.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "94.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "95.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "96.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "97.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "98.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "99.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "100.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "101.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "102.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "103.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "104.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "105.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "106.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "107.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "108.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "109.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "110.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "111.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "112.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "113.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "114.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "115.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "116.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "117.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "118.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "119.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "120.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "121.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "122.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "123.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "124.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "125.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "126.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "127.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "128.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "129.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "130.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "131.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "132.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "133.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "134.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "135.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "136.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "137.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "138.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "139.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "140.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "141.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "142.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "143.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "144.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "145.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "146.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "147.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "148.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "149.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "150.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "151.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "152.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "153.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "154.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "155.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "156.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "157.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "158.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "159.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "160.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "161.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "162.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "163.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "164.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "165.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "166.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "167.png"));
        pokemonList.add(new Pokemon(47, "Venomoth", "BUG", "POISON", "168.png"));


    }

    public List<Pokemon> getPokemonList(){
        return pokemonList;
    }
}
